path:
  dataset_dir: /demand-scss

  train_data_name: dccrn_noisy_vcc2018_train_16k
  eval_data_name: dccrn_noisy_vcc2018_eval_16k_snr5

  tst_dataset_dir: /esc50-all
  tst_data_name: dccrn_noisy_vcc2018_eval_16k_snr5

  norm_data_dir: norm
  norm_scp_dir: norm_scp
  exp_dir: exp
  convert_save_dir: convert
  spks_id_yml: config/spks-id.yml
  pre_trained_dir: pre_trained/cvctk-80k.pt
data:
  sample_rate: 16000
  fftl: 2048
  hop_len: &hop_len 80
  win_len: 320
  fmin: 50
  fmax: 7600
  mel_dim: &mel_dim 80
  sample_frames: 32
  n_speakers: &n_speakers 12
  #eval_utterances: 5
# training setting
training:
  batch_size: &batch_size 32
  resume: False
  resume_path:
  ## learning rate
  lr: 1e-4
  weight_decay: 0.0
  ## dropout rate
  #do_prob: 0.5
  n_steps: 400000
  scheduler:
    milestones:
      - 50000
      - 100000
      - 200000
    gamma: 0.5
  checkpoint_interval: 5000
  n_workers: 1
  gpus: 1
  gpu_id: 0 # c1 apex
model:
  encoder:
    in_channels: *mel_dim
    channels: 512
    n_embeddings:  512
    embedding_dim: &embedding_dim 64
    jitter: 0.0
  decoder:
    in_channels: *embedding_dim
    conditioning_channels: 128
    n_speakers: *n_speakers
    speaker_embedding_dim: 64
    #speaker_linear_dim: 64
    mu_embedding_dim: 256
    rnn_channels: 768
    fc_channels: 512
    bits: 9
    hop_length: *hop_len
